- name: install and run nginx
  hosts: localhost
  become: yes      #equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

